[package]
name = "oxidos"
version = "0.1.0"
edition = "2021"
authors = ["Enzyl"]

[dependencies]
# Tạm thời để trống hoặc chỉ để các thư viện thực sự cần như:
compiler_builtins = { version = "0.1.0", features = ["mem"] }

[profile.release]
panic = "abort"
